spring:
  profiles:
    active: @spring.profiles.active@

server:
  port: 9010

# mybatis puls
mybatis-plus:
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.dance.adio.entity
  global-config:
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: auto
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'

# 用户token过期时长
auth:
  user:
    token:
      timeout:
        app: 30

logging:
  level:
    org.springframework.web: info
    com.github.binarywang.demo.wx.miniapp: debug
    cn.binarywang.wx.miniapp: debug

# 第三方API相关信息
thirdparty:
  # 微信
  wechat:
    notify:
      refund: https://cac.xxx.com/cac-api/order/notify/refund
    miniapp:
      configs:
        - appid: wx
          secret: 8714
          #微信小程序消息服务器配置的token
          token: hu
          #微信小程序消息服务器配置的EncodingAESKey
          aesKey: KaH9ny
          msgDataFormat: JSON
          base-url: https://api.weixin.qq.com
          # 登录校验URL
          code2Session-url: /sns/jscode2session
  # 统软云物联网
  unisoft:
    appid: uty
    base-url: http://iot-api.unisoft.cn/utyVWcgh1u
    password: zz
    api:
      list: /device/list/
      control: /device/control/
  # 互亿无限短信
  ihuyi:
    appid: VM45
    apikey: 8cc2871b63
    context: 您的订单：【%s】将在30分钟后到期并且自动断电，请及时续费。
    base-url: http://api.vm.ihuyi.com/webservice
    api:
      sms: /sms.php?method=Submit
      voice: /voice.php?method=Submit



# 配置白名单路径
whitelist:
  urls:
    - /doc.html
    - /webjars/**
    - /favicon.ico
    - /**/v2/api-docs
    - /swagger-resources/**
    - /**/test/**
    - /**/user/register/**
    - /**/wx/login
    - /**/auth/code
    - /**/user/logout
    - /**/stores